---
resources:
  - name: resource-test
    type: git
    source:
      uri: https://github.com/pivotal-Jay-Wilson/test-docker-limit.git
      branch: main

jobs:
  - name: job-hello-world
    public: true
    plan:
      - get: resource-test
      - task: check-limits
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: 
              repository:  ubuntu
              tag: latest
              username: ((username))
              password: ((password))
          inputs:
            - name: resource-test   
          params:                       
            USERNAME: ((username))
            PASSWORD: ((password))
          run:
            path: /bin/sh
            args:
            - -c
            - |
              env
              apt-get -qq update
              apt-get -qq upgrade
              apt-get -qq install curl jq
              echo "rate limits"
              ./resource-test/test.sh
