---
resource_types:
- name: registry-image
  type: registry-image
  source:
    repository: concourse/registry-image-resource
    tag: 0.14.0
resources:
  - name: resource-test
    type: git
    source:
      uri: https://github.com/pivotal-Jay-Wilson/test-docker-limit.git
      branch: main

jobs:
  - name: job-hello-world
    public: true
    plan:
      - get: resource-test
      - task: check-limits
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: 
              repository:  ubuntu
              tag: latest
          inputs:
            - name: resource-test              
          run:
            path: /bin/sh
            args:
            - -c
            - |
              apt-get -qq update
              apt-get -qq upgrade
              apt-get -qq install curl jq
              echo "rate limits"
              ./resource-test/test.sh
